version: "3.8"

services:
  bootcampProjectDb:
    container_name: bootcampDb
    image: postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=bootcampProjectDb

  mongoDb:
    container_name: mongoDb
    image: mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=1234

